namespace GFEditor.Enums
{
    public enum AuctionTypeEnum: int
    {
        None = 0,
        Weapon_OneHandSword = 1,
        Weapon_OneHandHammer = 2,
        Weapon_OneHandAxe = 3,
        Weapon_TwoHandSword = 4,
        Weapon_TwoHandHammer = 5,
        Weapon_TwoHandAxe = 6,
        Weapon_Bow = 7,
        Weapon_Firearm = 8,
        Weapon_Relic = 9,
        Weapon_Staff = 10,
        Weapon_Shield = 11,
        Misc_CostumeOneHand = 12,
        Misc_CostumeTwoHand = 13,
        Armor_Head = 14,
        Armor_Body = 15,
        Armor_Legs = 16,
        Armor_Hands = 17,
        Armor_Feet = 18,
        Armor_Back = 19,
        Armor_SoulCrystal = 20,
        Misc_Backpack = 21,
        Misc_CostumeHead = 22,
        Misc_CostumeBack = 23,
        Supplies_Mining = 24,
        Supplies_Foraging = 25,
        Supplies_Hunting = 26,
        Supplies_Ammo = 27,
        Supplies_Quest = 28,
        Supplies_Recipe = 29,
        Supplies_Reputation = 30,
        Supplies_Specials = 31,
        Supplies_Talents = 32,
        Supplies_Stones = 33,
        Misc_SpriteMisc = 34,
        Misc_SpriteFurniture = 35,
        Misc_SpriteEmblem = 36,
        Misc_SpriteSummons = 37,
        Misc_Mount = 38,
        Supplies_Scroll = 39,
        Misc_Others = 40,
        Weapons_OneHandedMecha = 41,
        Weapons_TwoHandedMecha = 42,
        Weapons_HeavyCannon = 43,
        Misc_CostumeOutfit = 44,
        Weapons_Blades = 45,
        Weapons_CrystalKey = 46,
        Misc_Thrones = 47,
        AnyHolyEquipment = 48,
        Supplies_GasRawMaterial = 49,
        Supplies_PigmentRawMaterial = 50,
        Misc_Postcard = 51,
        Armor_Souvenir = 52
    }
}
