namespace GFEditor.Enums
{
    public enum EquipType: short
    {
        Unknown = -1,
        None = 0,
        Head = 1,
        Torso = 2,
        Pants = 3,
        Glove = 4,
        Feet = 5,
        Back = 6,
        OneHand = 7,
        LeftHand = 8,
        TwoHands = 9,
        Shoot = 10,
        Accessory = 11,
        Ammo = 13,
        Backpack = 14,
        SpellStoneA = 15,
        SpellStoneB = 16,
        SpellStoneC = 17,
        SpellStoneD = 18,
        ElfStoneA = 19,
        ElfStoneB = 20,
        ElfCap = 21,
        ElfClothes = 22,
        ElfFurnitureA = 23,
        ElfFurnitureB = 24,
        ElfFurnitureC = 25,
        ElfFloor = 26,
        ElfWall = 27,
        OneHandOnly = 28,
        AccessoryOnly = 29,
        SpellStoneE = 30,
        SpellStoneF = 31,
        SpellStoneG = 32,
        SpellStoneH = 33,
        IsleEquipA = 34,
        IsleEquipB = 35,
        IsleEquipC = 36,
        IsleEquipD = 37,
        IsleEquipE = 38,
        IsleEquipF = 39,
        IKRide = 40,
        GKRide = 41,
        SoulCrystal = 42,
        Souvenir = 43,
        Max = 44
    }
}
