namespace GFEditor.Utils
{
    public static class AlignementUtils
    {
        private static readonly Logger m_Log = LogManager.GetCurrentClassLogger();
        private static readonly TranslatedValues m_Translate = TranslateUtils.Json.TranslatedValues;

        public static string GetAlignementName(EAlignement align)
        {
            return align switch
            {
                EAlignement.eA_None => "None",
                EAlignement.eA_City01 => "City 01",
                EAlignement.eA_City02 => "City 02",
                EAlignement.eA_City03 => "City 03",
                EAlignement.eA_City04 => "City 04",
                EAlignement.eA_City05 => "City 05",
                EAlignement.eA_City06 => "City 06",
                EAlignement.eA_City07 => "City 07",
                EAlignement.eA_City08 => "City 08",
                EAlignement.eA_City09 => "City 09",
                EAlignement.eA_City10 => "City 10",
                EAlignement.eA_Group01 => "Group 01",
                EAlignement.eA_Group02 => "Group 02",
                EAlignement.eA_Group03 => "Group 03",
                EAlignement.eA_Group04 => "Group 04",
                EAlignement.eA_Group05 => "Group 05",
                EAlignement.eA_Group06 => "Group 06",
                EAlignement.eA_Group07 => "Group 07",
                EAlignement.eA_Group08 => "Group 08",
                EAlignement.eA_Group09 => "Group 09",
                EAlignement.eA_Group10 => "Group 10",
                EAlignement.eA_Elf01 => "Elf 01",
                EAlignement.eA_Elf02 => "Elf 02",
                EAlignement.eA_Elf03 => "Elf 03",
                EAlignement.eA_Elf04 => "Elf 04",
                EAlignement.eA_Elf05 => "Elf 05",
                EAlignement.eA_Elf06 => "Elf 06",
                EAlignement.eA_Elf07 => "Elf 07",
                EAlignement.eA_Elf08 => "Elf 08",
                EAlignement.eA_Elf09 => "Elf 09",
                EAlignement.eA_Elf10 => "Elf 10",
                EAlignement.eA_Elf11 => "Elf 11",
                EAlignement.eA_Elf12 => "Elf 12",
                EAlignement.eA_Elf13 => "Elf 13",
                EAlignement.eA_Elf14 => "Elf 14",
                EAlignement.eA_Elf15 => "Elf 15",
                EAlignement.eA_Elf16 => "Elf 16",
                EAlignement.eA_PKPalace => "PK Palace",
                EAlignement.eA_Group11 => "Group 11",
                EAlignement.eA_Group12 => "Group 12",
                EAlignement.eA_Group13 => "Group 13",
                EAlignement.eA_Group14 => "Group 14",
                EAlignement.eA_Group15 => "Group 15",
                EAlignement.eA_GroupEnd => "Group End",
                EAlignement.eA_End => "End",
                _ => "Unknown",
            };
        }

        public static int GetAlignementIDFromEnum(EAlignement align)
        {
            return align switch
            {
                EAlignement.eA_None => 0,
                EAlignement.eA_City01 => 1,
                EAlignement.eA_City02 => 2,
                EAlignement.eA_City03 => 3,
                EAlignement.eA_City04 => 4,
                EAlignement.eA_City05 => 5,
                EAlignement.eA_City06 => 6,
                EAlignement.eA_City07 => 7,
                EAlignement.eA_City08 => 8,
                EAlignement.eA_City09 => 9,
                EAlignement.eA_City10 => 10,
                EAlignement.eA_Group01 => 11,
                EAlignement.eA_Group02 => 12,
                EAlignement.eA_Group03 => 13,
                EAlignement.eA_Group04 => 14,
                EAlignement.eA_Group05 => 15,
                EAlignement.eA_Group06 => 16,
                EAlignement.eA_Group07 => 17,
                EAlignement.eA_Group08 => 18,
                EAlignement.eA_Group09 => 19,
                EAlignement.eA_Group10 => 20,
                EAlignement.eA_Elf01 => 21,
                EAlignement.eA_Elf02 => 22,
                EAlignement.eA_Elf03 => 23,
                EAlignement.eA_Elf04 => 24,
                EAlignement.eA_Elf05 => 25,
                EAlignement.eA_Elf06 => 26,
                EAlignement.eA_Elf07 => 27,
                EAlignement.eA_Elf08 => 28,
                EAlignement.eA_Elf09 => 29,
                EAlignement.eA_Elf10 => 30,
                EAlignement.eA_Elf11 => 31,
                EAlignement.eA_Elf12 => 32,
                EAlignement.eA_Elf13 => 33,
                EAlignement.eA_Elf14 => 34,
                EAlignement.eA_Elf15 => 35,
                EAlignement.eA_Elf16 => 36,
                EAlignement.eA_PKPalace => 37,
                EAlignement.eA_Group11 => 38,
                EAlignement.eA_Group12 => 39,
                EAlignement.eA_Group13 => 40,
                EAlignement.eA_Group14 => 41,
                EAlignement.eA_Group15 => 42,
                EAlignement.eA_GroupEnd => 43,
                EAlignement.eA_End => -1,
                _ => -1
            };
        }

        public static EAlignement GetEnumAlignementFromID(int id)
        {
            return id switch
            {
                0 => EAlignement.eA_None,
                1 => EAlignement.eA_City01,
                2 => EAlignement.eA_City02,
                3 => EAlignement.eA_City03,
                4 => EAlignement.eA_City04,
                5 => EAlignement.eA_City05,
                6 => EAlignement.eA_City06,
                7 => EAlignement.eA_City07,
                8 => EAlignement.eA_City08,
                9 => EAlignement.eA_City09,
                10 => EAlignement.eA_City10,
                11 => EAlignement.eA_Group01,
                12 => EAlignement.eA_Group02,
                13 => EAlignement.eA_Group03,
                14 => EAlignement.eA_Group04,
                15 => EAlignement.eA_Group05,
                16 => EAlignement.eA_Group06,
                17 => EAlignement.eA_Group07,
                18 => EAlignement.eA_Group08,
                19 => EAlignement.eA_Group09,
                20 => EAlignement.eA_Group10,
                21 => EAlignement.eA_Elf01,
                22 => EAlignement.eA_Elf02,
                23 => EAlignement.eA_Elf03,
                24 => EAlignement.eA_Elf04,
                25 => EAlignement.eA_Elf05,
                26 => EAlignement.eA_Elf06,
                27 => EAlignement.eA_Elf07,
                28 => EAlignement.eA_Elf08,
                29 => EAlignement.eA_Elf09,
                30 => EAlignement.eA_Elf10,
                31 => EAlignement.eA_Elf11,
                32 => EAlignement.eA_Elf12,
                33 => EAlignement.eA_Elf13,
                34 => EAlignement.eA_Elf14,
                35 => EAlignement.eA_Elf15,
                36 => EAlignement.eA_Elf16,
                37 => EAlignement.eA_PKPalace,
                38 => EAlignement.eA_Group11,
                39 => EAlignement.eA_Group12,
                40 => EAlignement.eA_Group13,
                41 => EAlignement.eA_Group14,
                42 => EAlignement.eA_Group15,
                43 => EAlignement.eA_GroupEnd,
                _ => EAlignement.eA_None
            };
        }
    }
}
